# Generated by Django 4.2.23 on 2025-08-17 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='联系我们', max_length=100, verbose_name='表单标题')),
                ('email_to', models.EmailField(max_length=254, verbose_name='接收邮箱')),
                ('success_message', models.TextField(default='感谢您的留言，我们会尽快回复您！', verbose_name='成功消息')),
            ],
            options={
                'verbose_name': '联系表单插件',
                'verbose_name_plural': '联系表单插件',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MedicalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='科室名称')),
                ('description', models.TextField(blank=True, verbose_name='科室描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='科室图片')),
            ],
            options={
                'verbose_name': '医疗科室',
                'verbose_name_plural': '医疗科室',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsListPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('limit', models.PositiveIntegerField(default=5, verbose_name='显示数量')),
                ('show_excerpt', models.BooleanField(default=True, verbose_name='显示摘要')),
                ('show_image', models.BooleanField(default=True, verbose_name='显示图片')),
            ],
            options={
                'verbose_name': '新闻列表插件',
                'verbose_name_plural': '新闻列表插件',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ServiceListPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('limit', models.PositiveIntegerField(default=8, verbose_name='显示数量')),
                ('show_price', models.BooleanField(default=True, verbose_name='显示价格')),
                ('show_image', models.BooleanField(default=True, verbose_name='显示图片')),
                ('department', models.ForeignKey(blank=True, help_text='留空显示所有科室的服务', null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_cms.medicaldepartment', verbose_name='科室')),
            ],
            options={
                'verbose_name': '服务列表插件',
                'verbose_name_plural': '服务列表插件',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('description', models.TextField(verbose_name='服务描述')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='服务时长(分钟)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_cms.medicaldepartment', verbose_name='所属科室')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='服务图片')),
            ],
            options={
                'verbose_name': '医疗服务',
                'verbose_name_plural': '医疗服务',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(unique=True, verbose_name='URL别名')),
                ('content', models.TextField(verbose_name='内容')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='摘要')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔多个标签', max_length=200, verbose_name='标签')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('featured_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='特色图片')),
            ],
            options={
                'verbose_name': '医疗新闻',
                'verbose_name_plural': '医疗新闻',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorListPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('limit', models.PositiveIntegerField(default=6, verbose_name='显示数量')),
                ('show_photo', models.BooleanField(default=True, verbose_name='显示照片')),
                ('show_bio', models.BooleanField(default=True, verbose_name='显示简介')),
                ('department', models.ForeignKey(blank=True, help_text='留空显示所有科室的医生', null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_cms.medicaldepartment', verbose_name='科室')),
            ],
            options={
                'verbose_name': '医生列表插件',
                'verbose_name_plural': '医生列表插件',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('resident', '住院医师'), ('attending', '主治医师'), ('associate', '副主任医师'), ('chief', '主任医师')], max_length=20, verbose_name='职称')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='专业特长')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可预约')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_cms.medicaldepartment', verbose_name='所属科室')),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='医生照片')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '医生',
                'verbose_name_plural': '医生',
                'ordering': ['department', 'title'],
            },
        ),
    ]
