# Generated by Django 4.2.23 on 2025-08-17 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('medical_cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='分类图片')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='medical_cms.productcategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductListPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('limit', models.PositiveIntegerField(default=12, verbose_name='显示数量')),
                ('show_featured_only', models.BooleanField(default=False, verbose_name='仅显示推荐商品')),
                ('show_price', models.BooleanField(default=True, verbose_name='显示价格')),
                ('show_stock', models.BooleanField(default=True, verbose_name='显示库存')),
                ('show_description', models.BooleanField(default=True, verbose_name='显示描述')),
                ('category', models.ForeignKey(blank=True, help_text='留空显示所有分类的商品', null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_cms.productcategory', verbose_name='商品分类')),
                ('department', models.ForeignKey(blank=True, help_text='留空显示所有科室的商品', null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_cms.medicaldepartment', verbose_name='相关科室')),
            ],
            options={
                'verbose_name': '商品列表插件',
                'verbose_name_plural': '商品列表插件',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL别名')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='简短描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('min_stock_level', models.PositiveIntegerField(default=5, verbose_name='最低库存')),
                ('sku', models.CharField(blank=True, max_length=100, unique=True, verbose_name='商品编码')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='条形码')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='重量(克)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='尺寸(长x宽x高cm)')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔多个标签', max_length=200, verbose_name='标签')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '上架'), ('inactive', '下架'), ('out_of_stock', '缺货')], default='draft', max_length=20, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_prescription_required', models.BooleanField(default=False, verbose_name='是否需要处方')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='生产厂家')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('usage_instructions', models.TextField(blank=True, verbose_name='使用说明')),
                ('side_effects', models.TextField(blank=True, verbose_name='副作用')),
                ('contraindications', models.TextField(blank=True, verbose_name='禁忌症')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='销售数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_cms.productcategory', verbose_name='商品分类')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_cms.medicaldepartment', verbose_name='相关科室')),
                ('featured_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_featured', to=settings.FILER_IMAGE_MODEL, verbose_name='主图片')),
                ('gallery_images', models.ManyToManyField(blank=True, related_name='product_gallery', to=settings.FILER_IMAGE_MODEL, verbose_name='商品图库')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_featured'], name='medical_cms_status_d78729_idx'), models.Index(fields=['category', 'status'], name='medical_cms_categor_e36a33_idx'), models.Index(fields=['department', 'status'], name='medical_cms_departm_130d5e_idx')],
            },
        ),
    ]
