# Generated by Django 4.2.23 on 2025-09-28 05:06

from django.db import migrations, models
import django.db.models.deletion
import medical_cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_cms', '0003_book_bookcategory_booktag_booktagrelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='医院名称')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL别名')),
                ('description', models.TextField(verbose_name='医院描述')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='简短描述')),
                ('address', models.CharField(max_length=500, verbose_name='医院地址')),
                ('phone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('website', models.URLField(blank=True, verbose_name='网站')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, verbose_name='评分')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=medical_cms.models.get_hospital_image_path, verbose_name='特色图片')),
                ('services_offered', models.TextField(blank=True, verbose_name='提供服务')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='标签')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '已上线'), ('inactive', '已下线')], default='draft', max_length=20, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_affiliated', models.BooleanField(default=False, verbose_name='是否合作')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '医院',
                'verbose_name_plural': '医院',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to=medical_cms.models.get_hospital_category_image_path, verbose_name='分类图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '医院分类',
                'verbose_name_plural': '医院分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='product',
            name='featured_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='主图片文件'),
        ),
        migrations.AddField(
            model_name='product',
            name='pharmacy_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='药店名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='视频标题', max_length=255, verbose_name='标题')),
                ('url', models.URLField(help_text='视频播放链接', verbose_name='视频链接')),
                ('cover_image', models.ImageField(blank=True, help_text='视频封面图片', null=True, upload_to=medical_cms.models.get_video_cover_path, verbose_name='封面图片')),
                ('duration', models.PositiveIntegerField(default=0, help_text='视频时长，单位：秒', verbose_name='时长(秒)')),
                ('description', models.TextField(blank=True, help_text='视频详细描述', verbose_name='描述')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔多个标签', max_length=200, verbose_name='标签')),
                ('category', models.CharField(blank=True, help_text='视频分类', max_length=100, verbose_name='分类')),
                ('upload_time', models.DateTimeField(blank=True, help_text='视频上传时间', null=True, verbose_name='上传时间')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='视频观看次数', verbose_name='观看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ['-created_at', '-upload_time'],
                'indexes': [models.Index(fields=['title'], name='medical_cms_title_f2de6b_idx'), models.Index(fields=['category'], name='medical_cms_categor_cb27ab_idx'), models.Index(fields=['id'], name='medical_cms_id_a278b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='HospitalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=medical_cms.models.get_hospital_image_path)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='medical_cms.hospital')),
            ],
            options={
                'verbose_name': '医院图库图片',
                'verbose_name_plural': '医院图库图片',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_cms.hospitalcategory', verbose_name='医院分类'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_cms.medicaldepartment', verbose_name='相关科室'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['status', 'is_featured'], name='medical_cms_status_155330_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['category', 'status'], name='medical_cms_categor_6ff5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['department', 'status'], name='medical_cms_departm_4eb3a3_idx'),
        ),
    ]
